/* 
 * Copyright 2012 ClinRisk Ltd.
 * 
 * This file is part of QDiabetes-2013 (http://qdiabetes.org, http://svn.clinrisk.co.uk/opensource/qdiabetes).
 * 
 * QDiabetes-2013 is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * QDiabetes-2013 is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with QDiabetes-2013.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Additional terms
 * 
 * The following disclaimer must be displayed alongside any risk score generated by this code.
 *   The initial version of this file, to be found at http://svn.clinrisk.co.uk/opensource/qdiabetes, faithfully implements QDiabetes-2013.
 *   We have released this code under the GNU Lesser General Public License to enable others to implement the algorithm faithfully.
 *   However, the nature of the GNU Lesser General Public License is such that we cannot prevent, for example, someone altering the coefficients.
 *   We stress, therefore, that it is the responsibility of the end user to check that the source that they receive produces the same results as the original code posted at http://svn.clinrisk.co.uk/opensource/qdiabetes.
 *   Inaccurate implementations of risk scores can lead to wrong patients being given the wrong treatment.
 * 
 * This file has been auto-generated.
 * XML source: Q68_qdiabetes_2013_1_1.xml
 * STATA dta time stamp: 15 Feb 2013 11:36
 * This file was created on: Fri 15 Feb 2013 11:40:42 GMT
 */

#include <math.h>
#include <string.h>
#include <stdio.h>
#include <Q68_qdiabetes_2013_1_1.h>
#include <utils.h>

static double type2_male_raw(
int age,int b_corticosteroids,int b_cvd,int b_treatedhyp,double bmi,int ethrisk,int fh_diab,int smoke_cat,int surv,double town,int debug
)
{
	double survivor[16] = {
		0,
		0.998213708400726,
		0.996353209018707,
		0.994382798671722,
		0.992213606834412,
		0.989733397960663,
		0.987064540386200,
		0.984254062175751,
		0.981255292892456,
		0.977990627288818,
		0.974455237388611,
		0.970843732357025,
		0.967315018177032,
		0.963437378406525,
		0.959633111953735,
		0.955690681934357
	};

	/* The conditional arrays */

	double Iethrisk[10] = {
		0,
		0,
		1.2366090720913343000000000,
		1.4716746107789032000000000,
		1.8073235649498174000000000,
		1.2056055595936399000000000,
		0.6032369975938766100000000,
		0.9095436207452737300000000,
		0.9137604632927512900000000,
		0.7123719045990779500000000
	};
	double Ismoke[5] = {
		0,
		0.1618238582395977700000000,
		0.1902020385619117000000000,
		0.3210636179312467100000000,
		0.4140001301797494600000000
	};

	/* Applying the fractional polynomial transforms */
	/* (which includes scaling)                      */

	double dage = age;
	dage=dage/10;
	double age_1 = log(dage);
	double age_2 = pow(dage,3);
	double dbmi = bmi;
	dbmi=dbmi/10;
	double bmi_1 = pow(dbmi,2);
	double bmi_2 = pow(dbmi,3);

	/* Centring the continuous variables */

	age_1 = age_1 - 1.496771812438965;
	age_2 = age_2 - 89.149559020996094;
	bmi_1 = bmi_1 - 6.832604885101318;
	bmi_2 = bmi_2 - 17.859918594360352;
	//town = town - -0.132148191332817;

if(debug) printf("a1: %6.2f, a2: %6.2f\n", age_1, age_2);
if(debug) printf("b1: %6.2f, b2: %6.2f\n", bmi_1, bmi_2);

	/* Start of Sum */
	double a=0;

	/* The conditional sums */

	a += Iethrisk[ethrisk];
	a += Ismoke[smoke_cat];

	/* Sum from continuous values */

	a += age_1 * 4.4205598323371680000000000;
	a += age_2 * -0.0041132238299394193000000;
	a += bmi_1 * 1.1169895991721528000000000;
	a += bmi_2 * -0.1793529530251269100000000;
	//a += town * 0.0291530815903822650000000;

	/* Sum from boolean values */

	a += b_corticosteroids * 0.2059811979905692400000000;
	a += b_cvd * 0.3914728454990503100000000;
	a += b_treatedhyp * 0.5010787979849035100000000;
	a += fh_diab * 0.8385800403428993500000000;

if(debug)
  printf("tr:%5.2f, rl:%5.2f\n",
  b_treatedhyp * 0.5010787979849035100000000,
  fh_diab * 0.8385800403428993500000000
  );

	/* Sum from interaction terms */

	a += age_1 * bmi_1 * 0.5051031253768063500000000;
	a += age_1 * bmi_2 * -0.1375233635462656000000000;
	a += age_1 * fh_diab * -1.1463560542602569000000000;
	a += age_2 * bmi_1 * -0.0015800686452772700000000;
	a += age_2 * bmi_2 * 0.0003394090057824062300000;
	a += age_2 * fh_diab * 0.0018524160353981260000000;

if(debug){
  printf("i:%6.2f u:%6.2f l:%6.2f er:%6.2f\n",
    Iethrisk[ethrisk]+
    Ismoke[smoke_cat]+
    bmi_1 * 1.1169895991721528000000000+
    bmi_2 * -0.1793529530251269100000000+
    b_treatedhyp * 0.5010787979849035100000000+
    b_corticosteroids * 0.2059811979905692400000000+
    b_cvd * 0.3914728454990503100000000+
    fh_diab * 0.8385800403428993500000000,

    age_1 * bmi_1 * 0.5051031253768063500000000+
    age_1 * bmi_2 * -0.1375233635462656000000000+
    age_1 * fh_diab * -1.1463560542602569000000000,

    age_2 * bmi_1 * -0.0015800686452772700000000+
    age_2 * bmi_2 * 0.0003394090057824062300000+
    age_2 * fh_diab * 0.0018524160353981260000000,

    Iethrisk[ethrisk]
  );
}
	/* Calculate the score itself */
	double score = 100.0 * (1 - pow(survivor[surv], exp(a)) );
	return score;
}

static int type2_male_validation(
int age,int b_corticosteroids,int b_cvd,int b_treatedhyp,double bmi,int ethrisk,int fh_diab,int smoke_cat,int surv,double town,char *errorBuf,int errorBufSize
)
{
	int ok=1;
	*errorBuf=0;
	if (!i_in_range(age,25,84)) {
		ok=0;
		strlcat(errorBuf,"error: age must be in range (25,84)\n",errorBufSize);
	}
	if (!is_boolean(b_corticosteroids)) {
		ok=0;
		strlcat(errorBuf,"error: b_corticosteroids must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_cvd)) {
		ok=0;
		strlcat(errorBuf,"error: b_cvd must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_treatedhyp)) {
		ok=0;
		strlcat(errorBuf,"error: b_treatedhyp must be in range (0,1)\n",errorBufSize);
	}
	if (!d_in_range(bmi,20,40)) {
		ok=0;
		strlcat(errorBuf,"error: bmi must be in range (20,40)\n",errorBufSize);
	}
	if (!i_in_range(ethrisk,1,9)) {
		ok=0;
		strlcat(errorBuf,"error: ethrisk must be in range (1,9)\n",errorBufSize);
	}
	if (!is_boolean(fh_diab)) {
		ok=0;
		strlcat(errorBuf,"error: fh_diab must be in range (0,1)\n",errorBufSize);
	}
	if (!i_in_range(smoke_cat,0,4)) {
		ok=0;
		strlcat(errorBuf,"error: smoke_cat must be in range (0,4)\n",errorBufSize);
	}
	if (!i_in_range(surv,1,10)) {
		ok=0;
		strlcat(errorBuf,"error: surv must be in range (1,10)\n",errorBufSize);
	}
	if (!d_in_range(town,-7,11)) {
		ok=0;
		strlcat(errorBuf,"error: town must be in range (-7,11)\n",errorBufSize);
	}
	return ok;
}

double type2_male(
int age,int b_corticosteroids,int b_cvd,int b_treatedhyp,double bmi,int ethrisk,int fh_diab,int smoke_cat,int surv,double town,int *error,char *errorBuf,int errorBufSize,int debug
)
{/*
	*error = 0;	int ok = type2_male_validation(age,b_corticosteroids,b_cvd,b_treatedhyp,bmi,ethrisk,fh_diab,smoke_cat,surv,town,errorBuf,errorBufSize);
	if(!ok) { 
		*error = 1;
		return 0.0;
	} */
	return type2_male_raw(age,b_corticosteroids,b_cvd,b_treatedhyp,bmi,ethrisk,fh_diab,smoke_cat,surv,town,debug);
}
